// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByoeTPW6GZRh7J4GHtIjn5XpZfKkuwUcY',
    appId: '1:890384030566:android:2b95d600af0e1967cfc6a7',
    messagingSenderId: '890384030566',
    projectId: 'grabbit-a5d27',
    databaseURL: 'https://grabbit-a5d27-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'grabbit-a5d27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGaSJhDY0-AZFEECu0cAmEjRXooNwKwfc',
    appId: '1:890384030566:ios:0a016618119dbf27cfc6a7',
    messagingSenderId: '890384030566',
    projectId: 'grabbit-a5d27',
    databaseURL: 'https://grabbit-a5d27-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'grabbit-a5d27.appspot.com',
    iosClientId: '890384030566-jje5vhteciticfh7ceej14p27cq4m150.apps.googleusercontent.com',
    iosBundleId: 'com.grabbitapp.app',
  );
}
